# Diversity主题默认标题
title: Diversity
# Diversity主题默认描述
description: 博客多样性，一款多主题自由切换的Hexo主题
# 当网页链接被分享到社交平台时显示的图片URL
image: /images/diversity.png
# Favicon路径【一个小型图标，用于在浏览器的标签页、地址栏或书签栏中标识和区分不同的网站】
favicon: /images/diversity.ico
# 主题图片翻转后的背景图片
back_image: /images/back.jpg

# 多主题图片路径
path:
  # 以 landscape 主题举例：
  # 如果该图片路径未配置，默认取 /images/default.png
  landscape: /images/landscape.jpg
  phase: /images/phase.png
  light: /images/light.jpg

# 主题项目来源【如果没有配置，则主题来源按钮点击无反应】
source:
  landscape: https://github.com/hexojs/hexo-theme-landscape
  phase: https://github.com/hexojs/hexo-theme-phase
  light: https://github.com/hexojs/hexo-theme-light
