# Diversity主题默认标题
title: Diversity
# Diversity主题默认描述
description: 博客多样性，一款多主题自由切换的Hexo主题
# 当网页链接被分享到社交平台时显示的图片URL
image: /images/diversity.png
# Favicon路径【一个小型图标，用于在浏览器的标签页、地址栏或书签栏中标识和区分不同的网站】
favicon: /images/diversity.ico
# 主题图片翻转后的背景图片
back_image: /images/back.jpg

# 深色模式，可选值： 0（关闭） | 1（跟随系统）| 2（手动切换）
darkmode: 0

# 多主题图片路径
path:
  # 以 landscape 主题举例：
  # 如果该图片路径未配置，默认取 /images/default.png
  landscape: /images/landscape.jpg
  phase: /images/phase.png
  light: /images/light.jpg

# 主题项目来源【如果没有配置，则主题来源按钮点击无反应】
source:
  landscape: https://github.com/hexojs/hexo-theme-landscape
  phase: https://github.com/hexojs/hexo-theme-phase
  light: https://github.com/hexojs/hexo-theme-light

# 页面配置
page:
  # 博客页滚动高度【单位：px】
  # 滚动页面高度大于等于配置高度，隐藏菜单导航栏
  # 滚动页面高度小于配置高度，显示菜单导航栏
  blog_scroll_height: 200

# 返回顶部按钮配置
back2top:
  # 是否启用，可选值： true | false
  enable: true
  # 返回顶部按钮中是否启用展示滚动百分比，可选值： true | false
  # Whether to enable displaying the scroll percent label in b2t button. Available values: true | false
  enable_scroll_percent: false
  # 展示返回顶部按钮的最少滚动百分比，建议值： 2 | 3 | 4 | 5
  # Minimum scroll percentage to display the b2t button, recommended values: 2 | 3 | 4 | 5
  scroll_percent: 5
  # 返回顶部按钮展示位置，可选值： left | right
  # B2t button position. Available values: left | right
  position: right
  # 鼠标悬浮或按钮激活时，返回顶部按钮的内容所展示的颜色
  # The color displayed when the mouse hovers over b2t button or the b2t button is activated.
  color: "#fc6423"
  # 被排除主题不展示返回顶部按钮
  # Excluded themes do not display the b2t button
  exclude: [next]

# 评论系统配置
comments:
  # 多个评论系统启用时，选择一个默认展示风格
  # 可选值：tabs 【选项卡】 
  # Available values: tabs
  style: tabs
  # 选择一个默认显示的评论系统
  # Choose a comment system to be displayed by default.
  # 可选值：utterances | gitalk | giscus
  # Available values: utterances | gitalk | giscus
  active:
  # 是否懒加载评论系统【true：是 false：否】
  # Lazyload all comment systems. Available values: true | false
  lazyload: false
  # 调整导航元素的展示文本或顺序
  # Modify texts or order for navigation elements
  nav:
    # 评论系统名，参考下方各评论系统定义
    #utterances:
    # 导航元素的展示文本
    #  text: Utterances
    # 导航元素的展示顺序
    #  order: 0
    #gitalk:
    #  order: 1

# Utterances
# 一个由开源社区构建的评论插件，它提供了一种在博客、文章或任何静态网站上添加互动式评论功能的高效解决方案。
# For more information: https://utteranc.es
utterances:
  # 可选值：true 【启用】 | false 【禁用】
  # Available values: true | false
  enable: false
  # 是否启用加载提示，可选值：true | false
  # Whether to enable loading indicator, Available values: true | false
  loading: true
  # GitHub 仓库所有者 user-name 和 名称 repo-name
  # Github repository owner and name
  repo: user-name/repo-name
  # 指定GitHub issue的匹配规则
  # Available values: pathname | url | title | og:title | `issue number` | `specific term`
  issue_term: pathname
  # 默认主题
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light
  # 深色主题
  # Dark Theme
  dark: github-dark

# Gitalk
# 一个基于GitHub Issue和Preact开发的现代评论插件。
# 它允许网站访客使用GitHub账号登录并发表评论，所有评论数据都储存在相应的GitHub仓库中。
# For more information: https://gitalk.github.io
gitalk:
  # 可选值：true 【启用】 | false 【禁用】
  # Available values: true | false
  enable: false
  # GitHub 仓库所有者
  # GitHub repo owner 
  github_id: 
  # 用于存储评论issues的GitHub仓库名
  # Repository name to store issues
  repo: 
  # GitHub 应用客户端 ID
  # GitHub Application Client ID
  client_id: 
  # GitHub 应用客户端密钥
  # GitHub Application Client Secret
  client_secret: 
  # GitHub 仓库所有者和协作者，只有这些人可以创建 GitHub issues。
  # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  admin_user: 
  # 类似 Facebook 的免打扰模式
  # Facebook-like distraction free mode
  distraction_free_mode: true 
  # 当官方代理不可用时，您可以将其更改为自己的代理地址。
  # When the official proxy is not available, you can change it to your own proxy address
  # 下面是官方代理地址
  # This is official proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token
  # 指定GitHub issue的匹配规则
  # 其中 pathname | url | title 用来匹配 issue 的标签，`issue number` 是 issue的编号（一个正数）
  # Available values: pathname | url | title | `issue number`
  issue_term: pathname
  # Gitalk 的显示语言取决于用户的浏览器或系统环境。
  # Gitalk's display language depends on user's browser or system environment
  # 如果您希望所有访问您网站的用户看到统一的语言，您可以设置一个强制语言值。
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language:

# Giscus
# 一个利用 GitHub Discussions 实现的评论系统
# For more information: https://giscus.app/
giscus:
  # 可选值：true 【启用】 | false 【禁用】
  # Available values: true | false
  enable: false
  # 是否启用加载提示，可选值：true | false
  # Whether to enable loading indicator, Available values: true | false
  loading: true
  # GitHub 仓库名称，指定评论数据存储在哪个 GitHub 仓库的 Discussions 中。
  # Github repository name
  repo: your-username/your-repo-name
  # GitHub 仓库的唯一ID
  # 调用 GitHub API https://api.github.com/repos/your-username/your-repo-name，
  # 返回的 JSON 中 node_id 字段即为仓库 ID
  # Github repository id
  repo_id: 
  # GitHub Discussions 分类名称。将评论归类到特定讨论板块，方便管理
  # Github discussion category
  category: 
  # Discussions 分类的唯一 ID。 需从 GitHub 获取，与 category 配合使用
  # Github discussion category id
  category_id: 
  # 指定GitHub discussion的匹配规则
  # 可选值： pathname | url | title | og:title | specific
  # Available values: pathname | url | title | og:title | specific
  mapping: pathname
  # 当 mapping 为 specific 时，该值必须配置，如下：
  # - Discussion 的标题包含特定字符串
  # - 特定 discussion 号
  term: 
  # 当 mapping 为 pathname 或 url 时，是否启用严格匹配 
  # 可选值:
  # 0-允许路径前缀匹配（如 https://example.com/post 匹配 https://example.com/post/1）
  # 1-仅完全匹配路径或 URL
  # Available values: 0 | 1
  strict: 0
  # 是否启用主帖子上的反应。启用后，Discussion 的主帖子上的反应将会显示在评论前
  # 可选值：0（关闭）| 1（启用）
  # Available values: 0 | 1
  reactions_enabled: 1
  # 是否向 GitHub 发送页面元数据（如标题、URL）
  # 可选值：0（不发送）| 1（发送）
  # Available values: 0 | 1
  emit_metadata: 0
  # 评论区的主题样式(默认主题)
  # 可选值：light | light_high_contrast | light_protanopia | light_tritanopia | dark | dark_high_contrast | dark_protanopia | dark_tritanopia | dark_dimmed | preferred_color_scheme | transparent_dark | noborder_light | noborder_dark | noborder_gray | cobalt | purple_dark
  # Available values: light | light_high_contrast | light_protanopia | light_tritanopia | dark | dark_high_contrast | dark_protanopia | dark_tritanopia | dark_dimmed | preferred_color_scheme | transparent_dark | noborder_light | noborder_dark | noborder_gray | cobalt | purple_dark
  theme: light
  # 深色主题
  # Dark Theme
  dark: dark
  # 评论区的语言（界面文本） 如果配置为空，则取 window.navigator.language
  # 可选值：en | es-ES | fr | ru | zh-CN | zh-TW
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  lang: 
  # 评论输入框的位置
  # 可选值：
  # bottom-将评论输入框固定在页面的底部（评论列表下方）
  # top-将评论输入框固定在页面的顶部（评论列表上方）
  # Place the comment box above the comments
  input_position: bottom
  # 懒加载评论
  # Load the comments lazily
  data_loading: lazy