# Diversity主题默认标题
title: Diversity
# Diversity主题默认描述
description: 博客多样性，一款多主题自由切换的Hexo主题
# 当网页链接被分享到社交平台时显示的图片URL
image: /images/diversity.png
# Favicon路径【一个小型图标，用于在浏览器的标签页、地址栏或书签栏中标识和区分不同的网站】
favicon: /images/diversity.ico
# 主题图片翻转后的背景图片
back_image: /images/back.jpg

# 多主题图片路径
path:
  # 以 landscape 主题举例：
  # 如果该图片路径未配置，默认取 /images/default.png
  landscape: /images/landscape.jpg
  phase: /images/phase.png
  light: /images/light.jpg

# 主题项目来源【如果没有配置，则主题来源按钮点击无反应】
source:
  landscape: https://github.com/hexojs/hexo-theme-landscape
  phase: https://github.com/hexojs/hexo-theme-phase
  light: https://github.com/hexojs/hexo-theme-light

# 页面配置
page:
  # 博客页滚动高度【单位：px】
  # 滚动页面高度大于等于配置高度，隐藏菜单导航栏
  # 滚动页面高度小于配置高度，显示菜单导航栏
  blog_scroll_height: 200

# 返回顶部按钮配置
back2top:
  # 是否启用，可选值： true | false
  enable: true
  # 返回顶部按钮中是否启用展示滚动百分比，可选值： true | false
  # Whether to enable displaying the scroll percent label in b2t button. Available values: true | false
  enable_scroll_percent: false
  # 展示返回顶部按钮的最少滚动百分比，建议值： 2 | 3 | 4 | 5
  # Minimum scroll percentage to display the b2t button, recommended values: 2 | 3 | 4 | 5
  scroll_percent: 5
  # 返回顶部按钮展示位置，可选值： left | right
  # B2t button position. Available values: left | right
  position: right
  # 鼠标悬浮或按钮激活时，返回顶部按钮的内容所展示的颜色
  # The color displayed when the mouse hovers over b2t button or the b2t button is activated.
  color: "#fc6423"
  # 被排除主题不展示返回顶部按钮
  # Excluded themes do not display the b2t button
  exclude: [next]

# 评论系统配置
comments:
  # 是否懒加载评论系统【true：是 false：否】
  lazyload: false

# Utterances
# 一个由开源社区构建的评论插件，它提供了一种在博客、文章或任何静态网站上添加互动式评论功能的高效解决方案。
# For more information: https://utteranc.es
utterances:
  # 可选值：true（启用） | false（禁用）
  # Available values: true | false
  enable: false
  # GitHub 仓库所有者 user-name 和 名称 repo-name
  # Github repository owner and name
  repo: user-name/repo-name
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light